package nl.agroqirax.calendartile

import java.text.Normalizer

/**
 * Picks a Material Symbols icon that represents an event, by matching keywords against its title
 * and location.
 *
 * Returns the icon's *name* rather than a drawable, which keeps this pure Kotlin and unit-testable
 * on the JVM; [TileIcons] turns a name into a resource.
 *
 * Keywords for every supported language live together in one table rather than in per-locale
 * resources, on purpose: event titles are written by whoever created the event, and routinely do
 * not match the device locale — a Dutch phone full of English work invites is the normal case, not
 * the exception.
 */
object EventIconMapper {

  /** Matches everything that is not a letter or a digit, i.e. the token separators. */
  private val SEPARATORS = Regex("[^\\p{L}\\p{N}]+")

  /** Combining accents left behind by NFD decomposition. */
  private val COMBINING_MARKS = Regex("\\p{Mn}+")

  /**
   * The built-in table, in the same [CustomIconRule] shape a decoded custom rule comes in — matched
   * by the same [matches] function below, so a keyword can be plain, regex, and/or exact here
   * exactly as it can in the custom-rules editor. Each entry is a synonym group for one icon, via
   * [CustomIconRule]'s list-of- keywords factory, so `.flatten()` below is what turns the groups
   * back into a single flat list of rules.
   *
   * Ordered most specific first — the first rule with a matching keyword wins. "Tandarts" must
   * reach `dentistry` before the more general `medical_services`, and "Teams meeting" must reach
   * `videocam` before `groups`.
   */
  private val RULES: List<CustomIconRule> =
      listOf(
              CustomIconRule(
                  listOf(
                      "dentist",
                      "dentistry",
                      "orthodontist",
                      "orthodontics",
                      "tandarts",
                      "gebit",
                      "mondhygienist",
                      "beugel",
                      "zahnarzt",
                      "kieferorthopade",
                      "dentiste",
                      "orthodontiste",
                      "dentista",
                      "ortodoncista",
                      "odontologia",
                  ),
                  TileIcons.DENTISTRY),
              CustomIconRule(
                  listOf(
                      "doctor",
                      "hospital",
                      "clinic",
                      "surgery",
                      "physio",
                      "physiotherapy",
                      "dokter",
                      "huisarts",
                      "ziekenhuis",
                      "kliniek",
                      "fysio",
                      "fysiotherapie",
                      "prik",
                      "arzt",
                      "krankenhaus",
                      "praxis",
                      "klinik",
                      "physiotherapie",
                      "medecin",
                      "hopital",
                      "clinique",
                      "kine",
                      "kinesitherapie",
                      "medico",
                      "hospital",
                      "clinica",
                      "consulta",
                      "fisioterapia",
                      "ospedale",
                      "dottore",
                      "visita",
                  ),
                  TileIcons.MEDICAL_SERVICES),
              CustomIconRule(
                  listOf(
                      "flight",
                      "flights",
                      "plane",
                      "airplane",
                      "aircraft",
                      "airport",
                      "boarding",
                      "vlucht",
                      "vliegtuig",
                      "vliegveld",
                      "luchthaven",
                      "schiphol",
                      "flug",
                      "flughafen",
                      "abflug",
                      "avion",
                      "aeroport",
                      "vuelo",
                      "aeropuerto",
                      "volo",
                      "aereo",
                      "aeroporto",
                      "voo",
                      "aviao",
                      // airports
                      "Schiphol",
                      "Heathrow",
                      "Gatwick",
                      "London Stansted",
                      "London Luton",
                      "Berlin Brandenburg",
                      "Paris Charles de Gaulle",
                      "Paris Orly",
                      "Madrid Barajas",
                      "Barcelona El Prat",
                      "Rome Fiumicino",
                      "Milan Malpensa",
                      "Milan Linate",
                      "Venice Marco Polo",
                      "Brussels South Charleroi",
                      "Stockholm Arlanda",
                      "Warsaw Chopin",
                      // airlines
                      "Ryanair",
                      "easyJet",
                      "Wizz Air",
                      "Turkish Airlines",
                      "Lufthansa",
                      "Pegasus Airlines",
                      "British Airways",
                      "Vueling",
                      "Air France",
                      "KLM",
                      "Iberia",
                      "Austrian Airlines",
                      "SWISS",
                      "Brussels Airlines",
                      "SAS",
                      "Norwegian",
                      "Finnair",
                      "TAP Air Portugal",
                      "TAP Portugal",
                      "Aer Lingus",
                      "Icelandair",
                      "ITA Airways",
                      "ITA",
                      "Alitalia",
                      "Eurowings",
                      "Condor",
                      "TUI fly",
                      "Transavia",
                      "Volotea",
                      "Air Europa",
                      "Air Serbia",
                      "Croatia Airlines",
                      "Aegean Airlines",
                      "LOT Polish Airlines",
                      "LOT",
                      "Smartwings",
                      "Widerøe",
                      "airBaltic",
                      "Luxair",
                      "Wizz Air Malta",
                      "Jet2",
                      "Jet2.com",
                      "Virgin Atlantic",
                      "Loganair",
                      "Ryanair UK",
                      "SunExpress",
                      "Corendon",
                      "Eurowings",
                      "Air Dolomiti",
                      "Edelweiss Air",
                      "Discover Airlines",
                      "Eurowings Discover",
                      "Condor",
                      "Bulgaria Air",
                      "TAROM",
                      "Air Nostrum",
                      "Iberia Express",
                      "Canaryfly",
                      "Binter Canarias",
                      "Neos",
                      "Air Corsica",
                      "Transavia France",
                      "Transavia Netherlands",
                      "Vueling Airlines",
                  ),
                  TileIcons.FLIGHT),

              // IATA route pairs, e.g. "AMS-JFK" or "AMS/JFK".
              // A lone code is too ambiguous with ordinary 3-letter acronyms
              CustomIconRule(
                  listOf(
                      "\\b[A-Z]{3}\\s*(?:-|/|→|->)\\s*[A-Z]{3}\\b",
                  ),
                  TileIcons.FLIGHT,
                  MatchMode.REGEX,
                  exact = true),
              CustomIconRule(
                  listOf(
                      "train",
                      "rail",
                      "railway",
                      "trein",
                      "spoor",
                      "intercity",
                      "zug",
                      "bahn",
                      "bahnhof",
                      "gare",
                      "tren",
                      "renfe",
                      "treno",
                      "stazione",
                      "comboio",
                      // operators
                      "SNCF",
                      "Deutsche Bahn",
                      "DB",
                      "Trenitalia",
                      "Renfe",
                      "NS",
                      "Nederlandse Spoorwegen",
                      "SNCB",
                      "NMBS",
                      "Eurostar",
                      "ÖBB",
                      "SBB",
                      "CFF",
                      "FFS",
                      "Italo",
                      "Ouigo",
                      "FlixTrain",
                      "Avanti West Coast",
                      "GWR",
                      "MÁV",
                      "ČD",
                      "RegioJet",
                      "European Sleeper",
                      "CP",
                      "Comboios de Portugal",
                      "RFI",
                      "Arriva",
                      "Abellio",
                      "Transdev",
                      "Keolis",
                      "Westbahn",
                      "SJ",
                      "DSB",
                      // brands
                      "ICE",
                      "Eurostar",
                      "TGV",
                      "TGV INOUI",
                      "OUIGO",
                      "AVE",
                      "Frecciarossa",
                      "Frecciargento",
                      "Frecciabianca",
                      "Italo",
                      "Railjet",
                      "Nightjet",
                      "EuroCity",
                      "EuroNight",
                      "Thalys",
                      "TGV Lyria",
                      "Thello",
                      "Cisalpino",
                      "Talgo",
                      "Alaris",
                      "Altaria",
                      "Euromed",
                      "City Night Line",
                      "European Sleeper",
                      "Bernina Express",
                      "Glacier Express",
                  ),
                  TileIcons.TRAIN),
              CustomIconRule(
                  listOf(
                      "hotel",
                      "motel",
                      "hostel",
                      "airbnb",
                      "bnb",
                      "overnachting",
                      "logies",
                      "unterkunft",
                      "pension",
                      "auberge",
                      "alojamiento",
                      "hospedaje",
                      "albergo",
                      "alloggio",
                      "pousada",
                      "b&b",
                      "hotels",
                  ),
                  TileIcons.HOTEL),
              CustomIconRule(
                  listOf(
                      "holiday",
                      "holidays",
                      "vacation",
                      "beach",
                      "seaside",
                      "vakantie",
                      "strand",
                      "zomervakantie",
                      "meivakantie",
                      "urlaub",
                      "ferien",
                      "sommerferien",
                      "vacances",
                      "plage",
                      "conges",
                      "vacaciones",
                      "playa",
                      "vacanza",
                      "vacanze",
                      "spiaggia",
                      "ferias",
                      "praia",
                  ),
                  TileIcons.BEACH_ACCESS),
              CustomIconRule(
                  listOf(
                      "car",
                      "drive",
                      "driving",
                      "garage",
                      "roadtrip",
                      "carwash",
                      "auto",
                      "rijden",
                      "rijles",
                      "rijexamen",
                      "apk",
                      "autogarage",
                      "fahren",
                      "fahrschule",
                      "werkstatt",
                      "tuv",
                      "voiture",
                      "conduite",
                      "coche",
                      "carro",
                      "taller",
                      "macchina",
                      "guida",
                      "officina",
                      // car rentals
                      "Avis",
                      "Hertz",
                      "Enterprise",
                      "Europcar",
                      "Sixt",
                  ),
                  TileIcons.DIRECTIONS_CAR),
              CustomIconRule(
                  listOf(
                      "birthday",
                      "bday",
                      "verjaardag",
                      "jarig",
                      "taart",
                      "geburtstag",
                      "kuchen",
                      "anniversaire",
                      "gateau",
                      "cumpleanos",
                      "tarta",
                      "pastel",
                      "compleanno",
                      "torta",
                      "aniversario",
                      "bolo",
                  ),
                  TileIcons.CAKE),
              CustomIconRule(
                  listOf(
                      "party",
                      "wedding",
                      "celebration",
                      "anniversary",
                      "graduation",
                      "reception",
                      "feest",
                      "feestje",
                      "bruiloft",
                      "trouwen",
                      "huwelijk",
                      "borrel",
                      "viering",
                      "jubileum",
                      "feier",
                      "hochzeit",
                      "jubilaum",
                      "fete",
                      "mariage",
                      "celebration",
                      "fiesta",
                      "boda",
                      "celebracion",
                      "festa",
                      "matrimonio",
                      "nozze",
                      "casamento",
                  ),
                  TileIcons.CELEBRATION),
              CustomIconRule(
                  listOf(
                      "baby",
                      "kids",
                      "childcare",
                      "daycare",
                      "nursery",
                      "babysitter",
                      "babysit",
                      "kinderen",
                      "kinderopvang",
                      "oppas",
                      "creche",
                      "consultatiebureau",
                      "kinder",
                      "kita",
                      "kindergarten",
                      "kinderbetreuung",
                      "garderie",
                      "nounou",
                      "guarderia",
                      "ninos",
                      "asilo",
                      "bambini",
                      "criancas",
                  ),
                  TileIcons.CHILD_CARE),
              CustomIconRule(
                  listOf(
                      "haircut",
                      "barber",
                      "hairdresser",
                      "hair",
                      "salon",
                      "kapper",
                      "knippen",
                      "kapsalon",
                      "friseur",
                      "haare",
                      "coiffeur",
                      "peluqueria",
                      "barberia",
                      "parrucchiere",
                      "cabeleireiro",
                  ),
                  TileIcons.CONTENT_CUT),
              CustomIconRule(
                  listOf(
                      "vet",
                      "veterinary",
                      "dog",
                      "cat",
                      "puppy",
                      "kitten",
                      "dierenarts",
                      "hond",
                      "kat",
                      "huisdier",
                      "uitlaten",
                      "tierarzt",
                      "hund",
                      "katze",
                      "haustier",
                      "veterinaire",
                      "chien",
                      "chat",
                      "veterinario",
                      "perro",
                      "gato",
                      "cane",
                      "gatto",
                      "cao",
                  ),
                  TileIcons.PETS),
              CustomIconRule(
                  listOf(
                      "church",
                      "mass",
                      "prayer",
                      "bible",
                      "worship",
                      "kerk",
                      "kerkdienst",
                      "gebed",
                      "bijbel",
                      "kirche",
                      "gottesdienst",
                      "messe",
                      "andacht",
                      "eglise",
                      "priere",
                      "iglesia",
                      "misa",
                      "oracion",
                      "chiesa",
                      "messa",
                      "igreja",
                      "missa",
                  ),
                  TileIcons.CHURCH),
              CustomIconRule(
                  listOf(
                      "school",
                      "class",
                      "lesson",
                      "seminar",
                      "university",
                      "exam",
                      "college",
                      "tutorial",
                      "lessen",
                      "tentamen",
                      "examen",
                      "universiteit",
                      "hogeschool",
                      "ouderavond",
                      "schule",
                      "unterricht",
                      "vorlesung",
                      "prufung",
                      "universitat",
                      "ecole",
                      "cours",
                      "universite",
                      "examens",
                      "escuela",
                      "clase",
                      "universidad",
                      "colegio",
                      "scuola",
                      "lezione",
                      "esame",
                      "universita",
                      "escola",
                      "aula",
                      "prova",
                      // subjects
                      "math",
                      "wiskunde",
                      "mathe",
                      "mathematica",
                      "chemistry",
                      "scheikunde",
                      "chemie",
                      "physics",
                      "natuurkunde",
                      "naturkunde",
                  ),
                  TileIcons.SCHOOL),
              CustomIconRule(
                  listOf(
                      "study",
                      "studying",
                      "homework",
                      "reading",
                      "library",
                      "book",
                      "revision",
                      "studeren",
                      "huiswerk",
                      "lezen",
                      "boek",
                      "bibliotheek",
                      "lernen",
                      "hausaufgaben",
                      "bibliothek",
                      "buch",
                      "etudier",
                      "devoirs",
                      "bibliotheque",
                      "livre",
                      "estudiar",
                      "deberes",
                      "biblioteca",
                      "libro",
                      "studiare",
                      "compiti",
                      "estudar",
                      "livro",
                  ),
                  TileIcons.MENU_BOOK),
              CustomIconRule(
                  listOf(
                      "zoom",
                      "teams",
                      "webex",
                      "skype",
                      "videocall",
                      "hangout",
                      "facetime",
                      "webinar",
                      "videobellen",
                      "videogesprek",
                      "beeldbellen",
                      "videoanruf",
                      "videokonferenz",
                      "visio",
                      "visioconference",
                      "videollamada",
                      "videoconferencia",
                      "videochiamata",
                      "videoconferenza",
                      "videochamada",
                  ),
                  TileIcons.VIDEOCAM),
              CustomIconRule(
                  listOf(
                      "call",
                      "phone",
                      "phonecall",
                      "telephone",
                      "bellen",
                      "telefoon",
                      "telefoontje",
                      "anruf",
                      "telefonat",
                      "telefonieren",
                      "appel",
                      "llamada",
                      "telefono",
                      "chiamata",
                      "telefonata",
                      "telefonema",
                      "ligacao",
                  ),
                  TileIcons.CALL),
              CustomIconRule(
                  listOf(
                      "meeting",
                      "standup",
                      "sync",
                      "team",
                      "workshop",
                      "interview",
                      "1on1",
                      "retro",
                      "vergadering",
                      "overleg",
                      "bespreking",
                      "teamoverleg",
                      "sollicitatie",
                      "besprechung",
                      "treffen",
                      "sitzung",
                      "vorstellungsgesprach",
                      "reunion",
                      "entretien",
                      "junta",
                      "entrevista",
                      "riunione",
                      "colloquio",
                      "reuniao",
                  ),
                  TileIcons.GROUPS),
              CustomIconRule(
                  listOf(
                      "gym",
                      "workout",
                      "fitness",
                      "crossfit",
                      "pilates",
                      "yoga",
                      "bootcamp",
                      "sportschool",
                      "krachttraining",
                      "fitnessstudio",
                      "muckibude",
                      "musculation",
                      "gimnasio",
                      "palestra",
                      "ginasio",
                  ),
                  TileIcons.FITNESS_CENTER),
              CustomIconRule(
                  listOf(
                      "f1",
                      "formula 1",
                      "formula1",
                      "formule 1",
                      "formule1",
                      "formel 1",
                      "formel1",
                      "grand prix",
                      "grandprix",
                      "grote prijs",
                      "motogp",
                      "nascar",
                      "indycar",
                      "racing",
                      "qualifying",
                      "quali",
                      "autosport",
                      "rally",
                      "rallye",
                  ),
                  TileIcons.SPORTS_MOTORSPORTS),
              CustomIconRule(
                  listOf(
                      "launch",
                      "rocket",
                      "liftoff",
                      "raket",
                      "lancering",
                      "rakete",
                      "fusee",
                      "lancement",
                      "cohete",
                      "lanzamiento",
                      "razzo",
                      "lancio",
                      "foguete",
                      // companies/orgs
                      "spacex",
                      "space x",
                      "nasa",
                      "esa",
                      "jaxa",
                      "roscosmos",
                      "blue origin",
                      "cnsa",
                      "dlr",
                      // launch vehicles
                      "falcon 9",
                      "starship",
                      "artemis",
                      "soyuz",
                      "ariane",
                      "atlas v",
                      "electron",
                      "vega c",
                      "new glenn",
                      "long march",
                      // launch sites
                      "Vandenberg SFB",
                      "Cape Canaveral",
                  ),
                  TileIcons.ROCKET_LAUNCH),
              CustomIconRule(
                  listOf(
                      "football",
                      "soccer",
                      "match",
                      "tennis",
                      "hockey",
                      "basketball",
                      "padel",
                      "swimming",
                      "running",
                      "sport",
                      "sports",
                      "voetbal",
                      "wedstrijd",
                      "sporten",
                      "zwemmen",
                      "hardlopen",
                      "fussball",
                      "spiel",
                      "schwimmen",
                      "laufen",
                      "foot",
                      "natation",
                      "futbol",
                      "partido",
                      "natacion",
                      "deporte",
                      "calcio",
                      "partita",
                      "nuoto",
                      "corsa",
                      "futebol",
                      "jogo",
                      "desporto",
                  ),
                  TileIcons.SPORTS_SOCCER),
              CustomIconRule(
                  listOf(
                      "concert",
                      "gig",
                      "band",
                      "choir",
                      "orchestra",
                      "rehearsal",
                      "piano",
                      "guitar",
                      "muziek",
                      "koor",
                      "orkest",
                      "repetitie",
                      "gitaar",
                      "musik",
                      "chor",
                      "probe",
                      "gitarre",
                      "musique",
                      "chorale",
                      "repetition",
                      "guitare",
                      "musica",
                      "coro",
                      "ensayo",
                      "guitarra",
                      "orchestra",
                      "prova",
                      "chitarra",
                      "ensaio",
                  ),
                  TileIcons.MUSIC_NOTE),
              CustomIconRule(
                  listOf(
                      "movie",
                      "film",
                      "cinema",
                      "cinemas",
                      "premiere",
                      "theatre",
                      "theater",
                      "show",
                      "bioscoop",
                      "toneel",
                      "schouwburg",
                      "voorstelling",
                      "kino",
                      "spectacle",
                      "cine",
                      "pelicula",
                      "filme",
                      "teatro",
                      // streaming services
                      "Netflix",
                      "Amazon Prime Video",
                      "Hulu",
                      "HBO Max",
                      "Disney",
                      "Disney+",
                      "Paraount",
                      "Paramount+",
                      "Apple TV",
                      "AppleTV",
                      "Peacock",
                      // cinemas
                      "Pathé",
                      "Kinepolis",
                      "Vue",
                      "Cineworld",
                      "Odeon",
                      "Everyman",
                      "Showcase",
                      "Picturehouse",
                      "Curzon",
                      "Cineplex",
                      "Gaumont",
                      "Kinopolis",
                      "Cinemaxx",
                      "Cinesa",
                      "Yelmo",
                      "Cines",
                      "Ocine",
                      "Renoir",
                      "CineStar",
                      "Cineplexx",
                      "Cinecittà",
                      "Multikino",
                      "Helios",
                  ),
                  TileIcons.MOVIE),
              CustomIconRule(
                  listOf(
                      "coffee",
                      "cafe",
                      "breakfast",
                      "brunch",
                      "tea",
                      "koffie",
                      "ontbijt",
                      "thee",
                      "kaffee",
                      "fruhstuck",
                      "petitdejeuner",
                      "desayuno",
                      "cafeteria",
                      "caffe",
                      "colazione",
                      "pequenoalmoco",
                  ),
                  TileIcons.LOCAL_CAFE),
              CustomIconRule(
                  listOf(
                      "drinks",
                      "beer",
                      "bar",
                      "pub",
                      "cocktail",
                      "wine",
                      "aperitif",
                      "biertje",
                      "bier",
                      "kroeg",
                      "wijn",
                      "kneipe",
                      "wein",
                      "apero",
                      "aperitif",
                      "vin",
                      "cerveza",
                      "vino",
                      "copas",
                      "birra",
                      "aperitivo",
                      "cerveja",
                      "vinho",
                  ),
                  TileIcons.LOCAL_BAR),
              CustomIconRule(
                  listOf(
                      "dinner",
                      "lunch",
                      "restaurant",
                      "meal",
                      "supper",
                      "eten",
                      "diner",
                      "avondeten",
                      "lunchen",
                      "uiteten",
                      "essen",
                      "abendessen",
                      "mittagessen",
                      "kochen",
                      "dejeuner",
                      "souper",
                      "repas",
                      "cena",
                      "almuerzo",
                      "comida",
                      "pranzo",
                      "ristorante",
                      "jantar",
                      "almoco",
                  ),
                  TileIcons.RESTAURANT),
              CustomIconRule(
                  listOf(
                      "groceries",
                      "grocery",
                      "supermarket",
                      "market",
                      "boodschappen",
                      "supermarkt",
                      "markt",
                      "einkaufen",
                      "lebensmittel",
                      "wocheneinkauf",
                      "supermarche",
                      "marche",
                      "epicerie",
                      "supermercado",
                      "mercado",
                      "spesa",
                      "supermercato",
                      // brands
                      "Lidl",
                      "Aldi",
                      "Carrefour",
                      "SPAR",
                      "Auchan",
                      "Tesco",
                      "Kaufland",
                      "REWE",
                      "EDEKA",
                      "Leclerc",
                      "Intermarché",
                      "Système U",
                      "Mercadona",
                      "Eroski",
                      "Albert Heijn",
                      "Jumbo",
                      "Delhaize",
                      "Colruyt",
                      "Conad",
                      "Coop",
                      "Esselunga",
                      "PENNY",
                      "BILLA",
                      "Morrisons",
                      "Sainsbury's",
                      "Asda",
                      "Waitrose",
                      "Co-op",
                      "Ocado",
                      "Pingo Doce",
                      "Continente",
                      "Minipreço",
                      "Jerónimo Martins",
                      "Migros",
                      "Denner",
                      "Cora",
                      "Netto",
                      "MPreis",
                      "SuperValu",
                      "Dunnes Stores",
                  ),
                  TileIcons.GROCERY),
              CustomIconRule(
                  listOf(
                      "shopping",
                      "shop",
                      "mall",
                      "ikea",
                      "winkelen",
                      "shoppen",
                      "winkel",
                      "einkauf",
                      "shoppen",
                      "shopping",
                      "magasin",
                      "compras",
                      "tienda",
                      "acquisti",
                      "negozio",
                      "loja",
                  ),
                  TileIcons.SHOPPING_CART),
              CustomIconRule(
                  listOf(
                      "delivery",
                      "package",
                      "parcel",
                      "shipment",
                      "moving",
                      "removal",
                      "bezorging",
                      "pakket",
                      "levering",
                      "verhuizing",
                      "verhuizen",
                      "lieferung",
                      "paket",
                      "umzug",
                      "livraison",
                      "colis",
                      "demenagement",
                      "entrega",
                      "paquete",
                      "mudanza",
                      "consegna",
                      "pacco",
                      "trasloco",
                      "encomenda",
                      "mudanca",
                  ),
                  TileIcons.LOCAL_SHIPPING),
              CustomIconRule(
                  listOf(
                      "recycling",
                      "recycle",
                      "waste",
                      "afval",
                      "restafval",
                      "gft",
                      "vuilnis",
                      "kliko",
                      "afvalkalender",
                      "glasbak",
                      "oud papier",
                      "glas container",
                      "mull",
                      "abfall",
                      "altpapier",
                      "wertstoff",
                      "dechets",
                      "poubelle",
                      "basura",
                      "reciclaje",
                      "rifiuti",
                      "riciclaggio",
                      "lixo",
                      "reciclagem",
                  ),
                  TileIcons.RECYCLING),
              CustomIconRule(
                  listOf(
                      "cleaning",
                      "cleaner",
                      "laundry",
                      "chores",
                      "schoonmaak",
                      "schoonmaken",
                      "poetsen",
                      "wasgoed",
                      "stofzuigen",
                      "putzen",
                      "reinigung",
                      "wasche",
                      "menage",
                      "nettoyage",
                      "lessive",
                      "limpieza",
                      "colada",
                      "pulizia",
                      "bucato",
                      "limpeza",
                  ),
                  TileIcons.CLEANING_SERVICES),
              CustomIconRule(
                  listOf(
                      "bank",
                      "tax",
                      "taxes",
                      "mortgage",
                      "invoice",
                      "salary",
                      "budget",
                      "accountant",
                      "belasting",
                      "belastingaangifte",
                      "hypotheek",
                      "salaris",
                      "factuur",
                      "boekhouder",
                      "steuer",
                      "finanzamt",
                      "gehalt",
                      "rechnung",
                      "impots",
                      "banque",
                      "facture",
                      "salaire",
                      "impuestos",
                      "banco",
                      "factura",
                      "sueldo",
                      "tasse",
                      "banca",
                      "fattura",
                      "stipendio",
                      "imposto",
                      "fatura",
                      // banks
                      "ING",
                      "Rabobank",
                      "ABN AMRO",
                      "Bunq",
                      "Revolut",
                      "Barclays",
                      "HSBC",
                      "NatWest",
                      "Lloyds",
                      "Santander",
                      "Monzo",
                      "Nationwide",
                      "CaixaBank",
                      "BBVA",
                      "Sabadell",
                      "Bankinter",
                      "Unicaja",
                      "Commerzbank",
                      "Deutsche Bank",
                      "Postbank",
                      "DZ Bank",
                      "HypoVereinsbank",
                      "UniCredit",
                      "Erste Bank",
                      "Raiffeisen",
                      "Banca Intesa",
                      "Banco BPM",
                      "Mediobanca",
                      "FinecoBank",
                      "BPER Banca",
                      "Crédit Agricole",
                      "BNP Paribas",
                      "Société Générale",
                      "Crédit Mutuel",
                      "La Banque Postale",
                      "Banque Populaire",
                      "Caisse d'Épargne",
                      "Belfius",
                      "KBC",
                      "Argenta",
                      "Nordea",
                      "Danske Bank",
                      "Handelsbanken",
                      "Swedbank",
                      "SEB",
                      "DNB",
                      "SpareBank",
                      "Bank Norwegian",
                      "Bankinter",
                      "Millennium BCP",
                      "Novo Banco",
                      "Montepio",
                      "Caixa Geral de Depósitos",
                      "Erste Group",
                  ),
                  TileIcons.SAVINGS),
              CustomIconRule(
                  listOf(
                      "work",
                      "office",
                      "shift",
                      "deadline",
                      "oncall",
                      "werk",
                      "kantoor",
                      "dienst",
                      "ploegendienst",
                      "arbeit",
                      "buro",
                      "schicht",
                      "travail",
                      "bureau",
                      "trabajo",
                      "oficina",
                      "turno",
                      "lavoro",
                      "ufficio",
                      "trabalho",
                      "escritorio",
                  ),
                  TileIcons.WORK),
          )
          .flatten()

  /**
   * [RULES]' keywords, tokenised once here instead of on every [matches] call. The table has grown
   * past simple synonyms into full airport, airline and brand names, and a title that matches
   * nothing — the common case — walks every rule before giving up, re-tokenising each one's keyword
   * every time. Custom rules skip this: there are only ever a handful of them, so caching isn't
   * worth the complexity there.
   */
  private val RULE_TOKENS: Map<CustomIconRule, Set<String>> =
      RULES.filter { it.mode == MatchMode.WORDS }
          .associateWith { tokenize(it.keyword, fold = !it.exact) }

  /**
   * Returns the icon name for an event, or null when nothing matches — which is the common case,
   * and why callers need a fallback.
   *
   * The title is matched against every rule before the location is tried at all: a word in the
   * title is a far stronger signal than one that happens to appear in a venue name.
   */
  fun iconNameFor(
      title: String?,
      location: String?,
      customRules: List<CustomIconRule> = emptyList()
  ): String? = matchIn(title, customRules) ?: matchIn(location, customRules)

  /** Every icon this mapper can return. [TileIcons] must have a drawable for each. */
  val iconNames: Set<String>
    get() = RULES.mapTo(LinkedHashSet()) { it.iconName }

  /**
   * Custom rules are tried before the built-in table, but *within* one field. That keeps both
   * priorities intact: a custom keyword beats a built-in one, and the title still beats the
   * location either way.
   */
  private fun matchIn(text: String?, customRules: List<CustomIconRule>): String? {
    if (text.isNullOrBlank()) return null
    // Folded tokens serve every non-exact word rule, built-in or custom, so
    // they are computed once here. Exact and regex rules need the raw text and
    // do their own work per rule — both are rare.
    val tokens = tokenize(text)
    return customRules.firstOrNull { matches(it, text, tokens) }?.iconName
        ?: RULES.firstOrNull { matches(it, text, tokens) }?.iconName
  }

  /**
   * Whether one custom rule matches some text.
   *
   * Public so the rule editor's test box can run exactly what the tile runs, rather than an
   * approximation of it.
   */
  fun matches(rule: CustomIconRule, text: String): Boolean = matches(rule, text, tokenize(text))

  private fun matches(rule: CustomIconRule, raw: String, foldedTokens: Set<String>): Boolean =
      when (rule.mode) {
        // A keyword of several words matches only when all of them appear, so
        // "team lunch" is narrower than "lunch" rather than a synonym for it.
        MatchMode.WORDS -> {
          val haystack = if (rule.exact) tokenize(raw, fold = false) else foldedTokens
          val needed = RULE_TOKENS[rule] ?: tokenize(rule.keyword, fold = !rule.exact)
          needed.isNotEmpty() && haystack.containsAll(needed)
        }

        // Folding the haystack is what makes a pattern accent-insensitive; the
        // case flag is passed through so both halves of "ignore case and accents"
        // move together with the one switch.
        MatchMode.REGEX ->
            RegexMatching.containsMatchIn(
                pattern = rule.keyword,
                text = if (rule.exact) raw else fold(raw),
                caseSensitive = rule.exact)
      }

  /**
   * Splits text into a set of comparable words.
   *
   * Matching whole tokens rather than substrings is what stops "start" from looking like "art" and
   * "concerto" from matching every "concert" rule by accident. Accents are folded so "café" and
   * "cafe" behave identically, and German sharp s is expanded because it has no decomposed form.
   */
  private fun tokenize(text: String?, fold: Boolean = true): Set<String> {
    if (text.isNullOrBlank()) return emptySet()
    val prepared = if (fold) fold(text) else text
    return prepared.split(SEPARATORS).filterTo(mutableSetOf()) { it.isNotEmpty() }
  }

  /**
   * Strips the distinctions an "exact" rule wants to keep: case, accents, and the German sharp s,
   * which has no decomposed form and so needs expanding by hand.
   *
   * Note this is only about *comparison*. Splitting on non-letters happens either way — word
   * alignment is structural, not a normalisation the user can turn off.
   */
  private fun fold(text: String): String =
      Normalizer.normalize(text, Normalizer.Form.NFD)
          .replace(COMBINING_MARKS, "")
          .lowercase()
          .replace("ß", "ss")
}
