package nl.agroqirax.calendartile

/**
 * The event icons, and the drawable each one resolves to.
 *
 * Generated by tools/fetch-event-icons.sh — do not edit by hand.
 */
object TileIcons {

  const val BEACH_ACCESS = "beach_access"
  const val CAKE = "cake"
  const val CALL = "call"
  const val CELEBRATION = "celebration"
  const val CHILD_CARE = "child_care"
  const val CHURCH = "church"
  const val CLEANING_SERVICES = "cleaning_services"
  const val CONTENT_CUT = "content_cut"
  const val DENTISTRY = "dentistry"
  const val DIRECTIONS_CAR = "directions_car"
  const val FITNESS_CENTER = "fitness_center"
  const val FLIGHT = "flight"
  const val GROCERY = "grocery"
  const val GROUPS = "groups"
  const val HOTEL = "hotel"
  const val LOCAL_BAR = "local_bar"
  const val LOCAL_CAFE = "local_cafe"
  const val LOCAL_SHIPPING = "local_shipping"
  const val MEDICAL_SERVICES = "medical_services"
  const val MENU_BOOK = "menu_book"
  const val MOVIE = "movie"
  const val MUSIC_NOTE = "music_note"
  const val PETS = "pets"
  const val RECYCLING = "recycling"
  const val RESTAURANT = "restaurant"
  const val ROCKET_LAUNCH = "rocket_launch"
  const val SAVINGS = "savings"
  const val SCHOOL = "school"
  const val SHOPPING_CART = "shopping_cart"
  const val SPORTS_MOTORSPORTS = "sports_motorsports"
  const val SPORTS_SOCCER = "sports_soccer"
  const val TRAIN = "train"
  const val VIDEOCAM = "videocam"
  const val WORK = "work"

  /** Every icon, in a stable order, for the custom-mapping picker. */
  val all: Map<String, Int> =
      linkedMapOf(
          BEACH_ACCESS to R.drawable.ic_beach_access,
          CAKE to R.drawable.ic_cake,
          CALL to R.drawable.ic_call,
          CELEBRATION to R.drawable.ic_celebration,
          CHILD_CARE to R.drawable.ic_child_care,
          CHURCH to R.drawable.ic_church,
          CLEANING_SERVICES to R.drawable.ic_cleaning_services,
          CONTENT_CUT to R.drawable.ic_content_cut,
          DENTISTRY to R.drawable.ic_dentistry,
          DIRECTIONS_CAR to R.drawable.ic_directions_car,
          FITNESS_CENTER to R.drawable.ic_fitness_center,
          FLIGHT to R.drawable.ic_flight,
          GROCERY to R.drawable.ic_grocery,
          GROUPS to R.drawable.ic_groups,
          HOTEL to R.drawable.ic_hotel,
          LOCAL_BAR to R.drawable.ic_local_bar,
          LOCAL_CAFE to R.drawable.ic_local_cafe,
          LOCAL_SHIPPING to R.drawable.ic_local_shipping,
          MEDICAL_SERVICES to R.drawable.ic_medical_services,
          MENU_BOOK to R.drawable.ic_menu_book,
          MOVIE to R.drawable.ic_movie,
          MUSIC_NOTE to R.drawable.ic_music_note,
          PETS to R.drawable.ic_pets,
          RECYCLING to R.drawable.ic_recycling,
          RESTAURANT to R.drawable.ic_restaurant,
          ROCKET_LAUNCH to R.drawable.ic_rocket_launch,
          SAVINGS to R.drawable.ic_savings,
          SCHOOL to R.drawable.ic_school,
          SHOPPING_CART to R.drawable.ic_shopping_cart,
          SPORTS_MOTORSPORTS to R.drawable.ic_sports_motorsports,
          SPORTS_SOCCER to R.drawable.ic_sports_soccer,
          TRAIN to R.drawable.ic_train,
          VIDEOCAM to R.drawable.ic_videocam,
          WORK to R.drawable.ic_work,
      )

  /** Returns the drawable for [name], or null if there is no icon for it. */
  fun resIdFor(name: String): Int? = all[name]
}
