#!/usr/bin/env bash
#
# Downloads Material Symbols (outlined, 24px) VectorDrawables from Google's
# repo into app/src/main/res/drawable/, normalised to this project's house style.
#
# This script also regenerates TileIcons.kt, so that map can never drift from what is on disk.
#
# Usage: tools/fetch-event-icons.sh
#
set -euo pipefail

BASE_URL="https://raw.githubusercontent.com/google/material-design-icons/master/symbols/android"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Event glyphs live in their own resource root
CHROME_DIR="$REPO_ROOT/app/src/main/res/drawable"
DRAWABLE_DIR="$REPO_ROOT/app/src/main/res-event-icons/drawable"
TILE_ICONS_KT="$REPO_ROOT/app/src/main/java/nl/agroqirax/calendartile/TileIcons.kt"

# Icons used as UI chrome rather than event glyphs. Not part of the event map.
CHROME_ICONS=(
    add
    arrow_back
    calendar_today
    chevron_right
    delete
    match_case
    match_word
    regular_expression
    science
    today
    widgets
)

# Event glyphs, keyed by EventIconMapper's icon names (which are the official
# Material Symbols names). Keep this list sorted for readable diffs.
EVENT_ICONS=(
    beach_access
    cake
    call
    celebration
    child_care
    church
    cleaning_services
    content_cut
    dentistry
    directions_car
    fitness_center
    flight
    grocery
    groups
    hotel
    local_bar
    local_cafe
    local_shipping
    medical_services
    menu_book
    movie
    music_note
    pets
    recycling
    restaurant
    rocket_launch
    savings
    school
    shopping_cart
    sports_motorsports
    sports_soccer
    train
    videocam
    work
)

force=false
while getopts "f" opt; do
    case "$opt" in
        f) force=true ;;
        *) exit 1 ;;
    esac
done

fetch_icon() {
    local name="$1"
    local out_dir="$2"
    local url="$BASE_URL/$name/materialsymbolsrounded/${name}_fill1_24px.xml"
    local out="$out_dir/ic_${name}.xml"

    if [ -f "$out" ] && [ "$force" = false ]; then
        echo "  ic_${name}.xml (already exists, skipped)"
        return 0
    fi

    # Normalisations, both load-bearing:
    #  - Drop android:tint="?attr/colorControlNormal". SystemUI loads our drawable
    #    through a package context whose theme has no colorControlNormal, and it
    #    tints the tile icon itself anyway.
    #  - Use the same literal fill as the rest of the project's drawables.
    #
    # The tint is removed together with its preceding newline and indent, never
    # as a whole line: it is the last attribute in most of these files, so its
    # line carries the closing '>' of the <vector> tag. Deleting the line drops
    # that '>' and silently produces malformed XML. A few icons (autoMirrored
    # ones) put another attribute after the tint, so both shapes must work.
    if ! curl -sf "$url" \
        | perl -0pe 's/\n\s*android:tint="\?attr\/colorControlNormal"//g' \
        | sed 's|@android:color/white|#e3e3e3|' \
        > "$out"; then
        rm -f "$out"
        echo "  FAILED: $name (not found at $url)" >&2
        return 1
    fi

    # curl -f catches HTTP errors, but not a truncated body or a normalisation
    # that mangled the markup — so parse what we actually wrote.
    if ! xmllint --noout "$out" 2>/dev/null; then
        rm -f "$out"
        echo "  FAILED: $name (malformed XML after normalisation)" >&2
        return 1
    fi

    echo "  ic_${name}.xml"
}

generate_tile_icons_kt() {
    {
        echo "package nl.agroqirax.calendartile"
        echo
        echo "/**"
        echo " * The event icons, and the drawable each one resolves to."
        echo " *"
        echo " * Generated by tools/fetch-event-icons.sh — do not edit by hand."
        echo " */"
        echo "object TileIcons {"
        echo
        for name in "${EVENT_ICONS[@]}"; do
            echo "    const val ${name^^} = \"$name\""
        done
        echo
        echo "    /** Every icon, in a stable order, for the custom-mapping picker. */"
        echo "    val all: Map<String, Int> = linkedMapOf("
        for name in "${EVENT_ICONS[@]}"; do
            echo "        ${name^^} to R.drawable.ic_$name,"
        done
        echo "    )"
        echo
        echo "    /** Returns the drawable for [name], or null if there is no icon for it. */"
        echo "    fun resIdFor(name: String): Int? = all[name]"
        echo "}"
    } > "$TILE_ICONS_KT"
    tools/ktfmt.sh ${TILE_ICONS_KT#"$REPO_ROOT"/}
    echo "Generated ${TILE_ICONS_KT#"$REPO_ROOT"/} (${#EVENT_ICONS[@]} icons)"
}

mkdir -p "$DRAWABLE_DIR" "$CHROME_DIR"
failed=0

echo "Chrome icons -> ${CHROME_DIR#"$REPO_ROOT"/}"
for name in "${CHROME_ICONS[@]}"; do
    fetch_icon "$name" "$CHROME_DIR" || failed=$((failed + 1))
done

echo "Event icons -> ${DRAWABLE_DIR#"$REPO_ROOT"/}"
for name in "${EVENT_ICONS[@]}"; do
    fetch_icon "$name" "$DRAWABLE_DIR" || failed=$((failed + 1))
done

if [ "$failed" -gt 0 ]; then
    echo
    echo "$failed icon(s) failed — fix the names above before regenerating TileIcons.kt." >&2
    exit 1
fi

echo
generate_tile_icons_kt
